[package]
name = "trillium-rest-extras"
version = "0.1.1"
edition = "2021"

[dependencies]
trillium = "0.2.19"
trillium-router = "0.4.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
async-trait = "0.1.79"
casey = "0.4.0"
